from __future__ import annotations

import json
import logging
import os
from typing import Any
from uuid import UUID

import httpx
from app.config import settings

logger = logging.getLogger(__name__)

# All 12 context files + injection guide
CONTEXT_FILE_NAMES: list[str] = [
    "MASTER.md",
    "PRODUCT.md",
    "STACK.md",
    "ARCHITECTURE.md",
    "FOLDER_STRUCTURE.md",
    "SCHEMA.md",
    "API_SPEC.md",
    "BUSINESS_LOGIC.md",
    "ENV.md",
    "CONVENTIONS.md",
    "ANTI_PATTERNS.md",
    "DEPENDENCIES.md",
]


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_all_files(
    blueprint: dict[str, Any],
    project: Any,
    idea: dict[str, Any] | None = None,
) -> dict[str, str]:
    """
    Generate all 12 context files from blueprint data.
    Pure Python string generation — zero Claude API calls.
    Returns {filename: content}.
    """
    idea = idea or {}
    files: dict[str, str] = {
        "MASTER.md":          gen_master_md(blueprint, project),
        "PRODUCT.md":         gen_product_md(idea, project),
        "STACK.md":           gen_stack_md(blueprint),
        "ARCHITECTURE.md":    gen_architecture_md(blueprint),
        "FOLDER_STRUCTURE.md": gen_folder_structure_md(blueprint),
        "SCHEMA.md":          gen_schema_md(blueprint),
        "API_SPEC.md":        gen_api_spec_md(blueprint),
        "BUSINESS_LOGIC.md":  gen_business_logic_md(blueprint, idea),
        "ENV.md":             gen_env_md(blueprint),
        "CONVENTIONS.md":     gen_conventions_md(blueprint),
        "ANTI_PATTERNS.md":   gen_anti_patterns_md(blueprint),
        "DEPENDENCIES.md":    gen_dependencies_md(blueprint),
    }
    return files


# ── Individual generators ─────────────────────────────────────────────────────

def gen_master_md(blueprint: dict[str, Any], project: Any) -> str:
    arch = blueprint.get("architecture", {})
    arch_type = arch.get("type", "monolithic").capitalize()
    arch_reason = arch.get("reasoning", "")
    modules = blueprint.get("modules", [])
    module_lines = "\n".join(
        f"{i + 1}. {m.get('name', '')} — {m.get('description', '')}"
        for i, m in enumerate(modules)
        if isinstance(m, dict)
    )
    project_name = getattr(project, "name", "Project")
    complexity = blueprint.get("complexity_estimate", "Medium")

    return f"""# {project_name} — MASTER CONTEXT
# AUTO-GENERATED BY IDEAFORGE AI
# READ THIS FIRST. THEN READ REFERENCED FILES IN ORDER.
# DO NOT ask the user about anything defined in these files.

---

## WHAT IS BEING BUILT
{arch_type} application: {project_name}
Architecture reasoning: {arch_reason}
Complexity: {complexity}

## FILE READING ORDER
1. PRODUCT.md            → what + who + why
2. STACK.md              → exact tech, exact versions
3. ARCHITECTURE.md       → system design, component flow
4. FOLDER_STRUCTURE.md   → exact directory tree
5. SCHEMA.md             → database schema (implement exactly)
6. API_SPEC.md           → all endpoints (implement all)
7. BUSINESS_LOGIC.md     → rules, flows, calculations
8. ENV.md                → environment variables
9. CONVENTIONS.md        → naming, style rules
10. ANTI_PATTERNS.md     → never do these
11. DEPENDENCIES.md      → packages + install commands

## MODULES TO BUILD (in dependency order)
{module_lines}

## ABSOLUTE RULES
- Never deviate from defined stack
- Never create files outside FOLDER_STRUCTURE.md
- Never use a library not in DEPENDENCIES.md
- Always follow CONVENTIONS.md exactly
- Always implement error handling on every endpoint
- Always validate inputs server-side with Pydantic v2
- Use async def for every DB or external API operation
- Use SQLAlchemy 2.0 async patterns: select() + await session.execute()
- Use Pydantic v2: @field_validator, .model_dump(), not .dict()
- Return production-ready, complete code — no TODOs, no placeholders
"""


def gen_product_md(idea: dict[str, Any], project: Any) -> str:
    title = idea.get("title", getattr(project, "name", "Product"))
    description = idea.get("description", "")
    target_users = idea.get("target_users", "")
    core_features = idea.get("core_features", [])
    constraints = idea.get("constraints", [])
    tone = idea.get("tone", "professional")

    features_block = "\n".join(
        f"- {f}" for f in core_features
    ) or "- (see ARCHITECTURE.md for module breakdown)"
    constraints_block = "\n".join(f"- {c}" for c in constraints) or "- None specified"

    return f"""# PRODUCT.md — {title}

## What Is Being Built
{description}

## Who It's For
{target_users}

## Core Features
{features_block}

## Constraints
{constraints_block}

## Tone / Style
{tone.capitalize()}

## Success Criteria
- All core features functional end-to-end
- Authentication works with JWT httpOnly cookies
- API endpoints validated and returning correct shapes
- Frontend connected to all backend endpoints
- Deployed and publicly accessible
"""


def gen_stack_md(blueprint: dict[str, Any]) -> str:
    tech_stack = blueprint.get("tech_stack", {})
    sections: list[str] = ["# STACK.md\n# EXACT VERSIONS. NO ALTERNATIVES. NO DEVIATIONS.\n"]

    for layer, info in tech_stack.items():
        if layer == "deployment":
            continue
        if isinstance(info, dict):
            tech = info.get("tech", layer.capitalize())
            version = info.get("version", "latest")
            reasoning = info.get("reasoning", "")
            sections.append(
                f"## {layer.capitalize()}\n"
                f"Tech:       {tech} {version}\n"
                f"Reasoning:  {reasoning}\n"
            )

    deploy = tech_stack.get("deployment", {})
    if isinstance(deploy, dict):
        fe_host = deploy.get("frontend", "")
        be_host = deploy.get("backend", "")
        if fe_host or be_host:
            sections.append(
                f"## Deployment\n"
                f"Frontend:   {fe_host}\n"
                f"Backend:    {be_host}\n"
            )

    return "\n".join(sections)


def gen_architecture_md(blueprint: dict[str, Any]) -> str:
    arch = blueprint.get("architecture", {})
    tech_stack = blueprint.get("tech_stack", {})
    modules = blueprint.get("modules", [])
    integrations = blueprint.get("third_party_integrations", [])

    # Module dependency tree
    module_tree_lines: list[str] = []
    for m in modules:
        if not isinstance(m, dict):
            continue
        name = m.get("name", "")
        desc = m.get("description", "")
        deps = m.get("depends_on", [])
        sub = m.get("sub_components", [])
        dep_str = f" (depends on: {', '.join(deps)})" if deps else ""
        module_tree_lines.append(f"### {name}{dep_str}\n{desc}")
        if sub:
            module_tree_lines.append(
                "\nSub-components:\n" + "\n".join(f"- {s}" for s in sub)
            )

    # Tech layers
    fe = tech_stack.get("frontend", {})
    be = tech_stack.get("backend", {})
    db = tech_stack.get("database", {})
    ai = tech_stack.get("ai", {})

    int_lines = "\n".join(
        f"- {i}" if isinstance(i, str) else f"- {i.get('name', str(i))}"
        for i in integrations
    )

    return f"""# ARCHITECTURE.md

## Architecture Type
{arch.get("type", "monolithic").capitalize()}

## System Flow
```
User (Browser)
    ↕ HTTPS + WebSocket
Frontend ({fe.get("tech", "Next.js")})
    ↕ REST API + WebSocket
Backend API ({be.get("tech", "FastAPI")})
    ├── Database ({db.get("tech", "PostgreSQL")})
    ├── AI Layer ({ai.get("tech", "OpenAI")})
    └── External APIs
```

## Component Responsibilities
### Frontend ({fe.get("tech", "Next.js")})
- UI Rendering and Navigation
- Client-side validation
- Real-time WebSocket connection
- State management

### Backend ({be.get("tech", "FastAPI")})
- Business Logic Orchestration
- Database migrations and connections
- Third-party API coordination
- Authorization and Authentication

## Data Flow Per Stage
1. User → Browser → Frontend (SSR/CSR)
2. Frontend → Backend API (REST over HTTPS, JWT via httpOnly cookie)
3. Backend → Database (async ORM)
4. Backend → AI Provider (async HTTP client)
5. Backend → Third-party APIs (async HTTP client)
6. Backend → Frontend (WebSocket for real-time events)

## Request Lifecycle
1. Request hits Backend router
2. Dependency injection resolves: DB session, current_user
3. Router calls service layer (no business logic in router)
4. Service executes business logic, calls DB/AI/external APIs
5. Schema validates response shape
6. Response returned to client

## Third-Party Integrations
{int_lines or "None specified"}

## Application Modules
{chr(10).join(module_tree_lines) or "See modules list in MASTER.md"}
"""


def gen_folder_structure_md(blueprint: dict[str, Any]) -> str:
    folder_structure = blueprint.get("folder_structure", "")
    tech_stack = blueprint.get("tech_stack", {})
    be_tech = tech_stack.get("backend", {}).get("tech", "FastAPI")
    fe_tech = tech_stack.get("frontend", {}).get("tech", "Next.js")

    if folder_structure and len(folder_structure) > 100:
        # Blueprint provided a real folder structure
        return f"""# FOLDER_STRUCTURE.md

## Project Directory Tree
{folder_structure}

## Rules
- NEVER create files outside this structure
- NEVER add new top-level directories
- Follow the exact naming conventions in CONVENTIONS.md
"""

    # Generate a reasonable default based on the stack
    return f"""# FOLDER_STRUCTURE.md

## Project Directory Tree
/ (project root)
├── frontend/                    # {fe_tech} application
│   ├── app/                     # App Router (Next.js 14)
│   │   ├── layout.tsx           # Root layout
│   │   ├── page.tsx             # Home page
│   │   ├── (auth)/              # Auth route group
│   │   │   ├── login/page.tsx
│   │   │   └── register/page.tsx
│   │   └── dashboard/           # Protected pages
│   │       └── page.tsx
│   ├── components/              # Reusable UI components (PascalCase.tsx)
│   ├── lib/                     # Utilities + API clients (camelCase.ts)
│   ├── hooks/                   # Custom React hooks (useX.ts)
│   ├── types/                   # TypeScript type definitions
│   ├── public/                  # Static assets
│   ├── package.json
│   ├── tsconfig.json
│   ├── tailwind.config.ts
│   └── next.config.ts
├── backend/                     # {be_tech} application
│   ├── app/
│   │   ├── main.py              # FastAPI app init, router registration
│   │   ├── config.py            # Settings via pydantic-settings
│   │   ├── database.py          # Async SQLAlchemy engine + session
│   │   ├── models/              # SQLAlchemy ORM models
│   │   ├── schemas/             # Pydantic v2 request/response models
│   │   ├── routers/             # FastAPI routers (one per domain)
│   │   ├── services/            # Business logic (called by routers)
│   │   ├── core/                # Shared utilities (auth, encryption, etc.)
│   │   └── middleware/          # FastAPI middleware
│   ├── migrations/              # Alembic migrations
│   │   └── versions/
│   ├── tests/
│   ├── requirements.txt
│   └── .env
└── README.md

## Rules
- NEVER create files outside this structure
- NEVER add new top-level directories
- All router files: one per domain (auth.py, projects.py, etc.)
- All service files: snake_case, end in _service.py
- All model files: snake_case singular (user.py, project.py)
- All schema files: snake_case singular (auth.py, project.py)
"""


def gen_schema_md(blueprint: dict[str, Any]) -> str:
    db_schema = blueprint.get("database_schema", {})
    tables = db_schema.get("tables", [])
    sql_blocks: list[str] = []

    for table in tables:
        if not isinstance(table, dict):
            continue
        table_name = table.get("name", "unknown_table")
        fields = table.get("fields", [])
        indexes = table.get("indexes", [])
        notes = table.get("notes", "")

        field_lines: list[str] = []
        for field in fields:
            if not isinstance(field, dict):
                continue
            col_name = field.get("name", "")
            col_type = field.get("type", "TEXT")
            constraints = field.get("constraints", [])
            constraint_str = " ".join(constraints) if constraints else ""
            field_lines.append(f"  {col_name} {col_type} {constraint_str}".rstrip())

        rel_lines = []
        for rel in table.get("relationships", []):
            if isinstance(rel, str):
                rel_lines.append(f"  -- Relationship: {rel}")

        body = ",\n".join(field_lines)
        sql = f"CREATE TABLE {table_name} (\n{body}\n);"
        if notes:
            sql = f"-- {notes}\n{sql}"
        sql_blocks.append(sql)

        for idx in indexes:
            if isinstance(idx, str):
                sql_blocks.append(
                    f"CREATE INDEX {idx} ON {table_name} ({idx.split('_', 2)[-1]});"
                )

    if not sql_blocks:
        sql_blocks = [
            "-- Database schema will be generated from blueprint modules.\n"
            "-- Ensure UUID PKs, TIMESTAMPTZ timestamps, soft deletes where needed."
        ]

    return "# SCHEMA.md\n# Implement exactly as written. No deviations.\n\n" + "\n\n".join(sql_blocks)


def gen_api_spec_md(blueprint: dict[str, Any]) -> str:
    endpoints = blueprint.get("api_endpoints", [])
    tech_stack = blueprint.get("tech_stack", {})
    be_tech = tech_stack.get("backend", {}).get("tech", "FastAPI")

    lines: list[str] = [
        "# API_SPEC.md\n# IMPLEMENT ALL ENDPOINTS. EXACT ROUTES. EXACT METHODS.\n",
        f"Base URL: /api/v1\n"
        f"Backend:  {be_tech}\n"
        "Auth:     JWT via httpOnly cookie named 'access_token'\n",
        "---\n",
    ]

    # Group endpoints by prefix
    groups: dict[str, list[dict[str, Any]]] = {}
    for ep in endpoints:
        if not isinstance(ep, dict):
            continue
        route = ep.get("path", "")
        parts = route.strip("/").split("/")
        # Group by first meaningful segment after "api/v1"
        idx = next(
            (i for i, p in enumerate(parts) if p not in ("api", "v1")),
            len(parts) - 1,
        )
        group = parts[idx] if idx < len(parts) else "misc"
        groups.setdefault(group.upper(), []).append(ep)

    for group_name, group_eps in groups.items():
        lines.append(f"## {group_name}")
        for ep in group_eps:
            method = ep.get("method", "GET").upper()
            route = ep.get("path", "")
            desc = ep.get("description", "")
            auth = ep.get("auth_required", True)
            auth_str = "Required" if auth else "None"
            body = ep.get("body", {})
            returns = ep.get("returns", {})

            ep_block = f"{method:8} {route}\n  Auth:    {auth_str}\n  Desc:    {desc}"
            if body:
                ep_block += f"\n  Body:    {json.dumps(body, separators=(',', ':'))}"
            if returns:
                ep_block += f"\n  Returns: {json.dumps(returns, separators=(',', ':'))}"
            lines.append(ep_block)
        lines.append("")

    if not groups:
        lines.append(
            "Endpoints will be defined per module. Follow this pattern:\n"
            "  GET    /api/v1/{resource}           → list\n"
            "  POST   /api/v1/{resource}           → create\n"
            "  GET    /api/v1/{resource}/{id}      → detail\n"
            "  PATCH  /api/v1/{resource}/{id}      → update\n"
            "  DELETE /api/v1/{resource}/{id}      → delete\n"
        )

    return "\n".join(lines)


def gen_business_logic_md(blueprint: dict[str, Any], idea: dict[str, Any]) -> str:
    modules = blueprint.get("modules", [])
    complexity = blueprint.get("complexity_estimate", "Medium")
    cuts = blueprint.get("module_cut_suggestions", [])

    module_rules: list[str] = []
    for m in modules:
        if not isinstance(m, dict):
            continue
        name = m.get("name", "")
        desc = m.get("description", "")
        deps = m.get("depends_on", [])
        dep_str = f"Depends on: {', '.join(deps)}" if deps else "No dependencies"
        module_rules.append(
            f"### {name}\n{desc}\n{dep_str}"
        )

    cuts_block = "\n".join(f"- {c}" for c in cuts) if cuts else "None"
    features = idea.get("core_features", [])
    feature_block = "\n".join(f"- {f}" for f in features) if features else "See modules"

    return f"""# BUSINESS_LOGIC.md

## Complexity
{complexity}

## Core Features to Implement
{feature_block}

## Module Rules
{chr(10).join(module_rules) or "Build modules in dependency order as defined in MASTER.md"}

## General Rules
- Sequential operations: validate input → process → persist → respond
- Never trust user input: validate heavily on every endpoint
- Never expose internal errors to client: catch exceptions, return proper HTTP codes
- State transitions: only valid transitions allowed (enforce in service layer)
- Ownership: always verify resource belongs to authenticated user
- Idempotent writes: upsert where possible (avoid duplicate key errors)

## State Transitions (only these are valid)
```
DRAFT → PENDING (trigger: user submission)
PENDING → APPROVED (trigger: admin review)
PENDING → REJECTED (trigger: admin review)
APPROVED → ACTIVE (trigger: system process)
ACTIVE → ARCHIVED (trigger: user action)
```

## Error Classification
```json
{{
    "missing_dependency": "ModuleNotFoundError|ImportError",
    "auth_error": "401|Unauthorized|JWT",
    "syntax_error": "SyntaxError|unexpected token"
}}
```

## API Contract Rules
- All routes versioned: /api/v1/
- All responses use consistent error format: {{ detail, code, field }}
- Auth: read user_id from JWT token only — never from request body
- Pagination: cursor-based for large collections
- File uploads: validate MIME type and size before processing

## Module Cut Suggestions (High complexity only)
{cuts_block}
"""


def gen_env_md(blueprint: dict[str, Any]) -> str:
    tech_stack = blueprint.get("tech_stack", {})
    integrations = blueprint.get("third_party_integrations", [])
    env_vars = blueprint.get("environment_variables", [])

    lines: list[str] = [
        "# ENV.md\n# All required environment variables.\n"
        "# Copy to .env (backend) and .env.local (frontend). Never commit.\n",
        "## Backend (.env)\n",
    ]

    core_vars = [
        ("DATABASE_URL",       "postgresql+asyncpg://user:pass@host:5432/db",   "Async PostgreSQL URL"),
        ("SUPABASE_URL",       "https://your-project.supabase.co",              "Supabase project URL"),
        ("SUPABASE_SERVICE_KEY", "eyJ...",                                       "Supabase service_role key (never expose)"),
        ("JWT_SECRET",         "your-256-bit-secret",                           "JWT signing secret"),
        ("JWT_ALGORITHM",      "HS256",                                          "JWT algorithm"),
        ("FERNET_KEY",         "base64-encoded-32-byte-key",                    "Symmetric encryption key for API keys"),
        ("ENVIRONMENT",        "development",                                   "development | production"),
    ]

    for name, example, desc in core_vars:
        lines.append(f"# {desc}\n{name}={example}\n")

    for integration in integrations:
        int_name = integration if isinstance(integration, str) else integration.get("name", "")
        if not int_name:
            continue
        int_upper = int_name.upper().replace(" ", "_").replace("-", "_")
        lines.append(f"# {int_name} integration\n{int_upper}_API_KEY=your-key-here\n")

    if env_vars:
        lines.append("\n## Blueprint-specified Variables\n")
        for var in env_vars:
            if isinstance(var, dict):
                name = var.get("name", "")
                desc = var.get("description", "")
                example = var.get("example", "your-value")
                req = "Required" if var.get("required", True) else "Optional"
                lines.append(f"# {desc} ({req})\n{name}={example}\n")

    lines.append("\n## Frontend (.env.local)\n")
    lines.append("NEXT_PUBLIC_API_URL=http://localhost:8000")
    lines.append("NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co")
    lines.append("NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJ...")

    return "\n".join(lines)


def gen_conventions_md(blueprint: dict[str, Any]) -> str:
    tech_stack = blueprint.get("tech_stack", {})
    be_tech = tech_stack.get("backend", {}).get("tech", "FastAPI")
    fe_tech = tech_stack.get("frontend", {}).get("tech", "Next.js")

    return f"""# CONVENTIONS.md
# FOLLOW EXACTLY. NO EXCEPTIONS.

## Python (Backend — {be_tech})
files:        snake_case              (user_service.py)
classes:      PascalCase              (UserService)
functions:    snake_case              (get_user_by_id)
variables:    snake_case              (user_api_key)
constants:    UPPER_SNAKE_CASE        (MAX_RETRY_COUNT = 3)
async:        ALL DB + API calls must use async def
type hints:   required on every function signature
docstrings:   one-line for simple functions; skip obvious ones

## TypeScript (Frontend — {fe_tech})
files:        PascalCase.tsx          (UserCard.tsx) for components
files:        camelCase.ts            (useAuth.ts) for hooks/lib
components:   PascalCase              (UserCard)
functions:    camelCase               (getUserById)
variables:    camelCase               (userApiKey)
types:        PascalCase              (UserResponse, ApiError)
constants:    UPPER_SNAKE_CASE        (MAX_ROUNDS = 3)

## Database
tables:       snake_case plural       (user_api_keys)
columns:      snake_case              (created_at, user_id)
indexes:      idx_{{table}}_{{column}}    (idx_users_email)
PKs:          Always UUID with DEFAULT gen_random_uuid()
timestamps:   Always TIMESTAMPTZ

## API Routes
paths:        kebab-case              (/api/v1/user-api-keys)
path params:  snake_case in Python    (user_id: UUID)
prefix:       Always /api/v1/

## FastAPI Patterns
router:       One per domain in routers/ — never cross-domain
services:     Business logic ONLY in services/ — never in routers
models:       SQLAlchemy models in models/
schemas:      Pydantic v2 in schemas/
utilities:    Shared code in core/
auth dep:     Depends(get_current_user)
db dep:       Depends(get_db)

## Error Response Format
```json
{{"detail": "Human readable message", "code": "MACHINE_READABLE", "field": "field_name"}}
```

## SQLAlchemy 2.0 Patterns
```python
# CORRECT
result = await db.execute(select(User).where(User.id == user_id))
user = result.scalar_one_or_none()

# WRONG — never do this
user = db.query(User).filter(User.id == user_id).first()
```

## Pydantic v2 Patterns
```python
# CORRECT
class MyModel(BaseModel):
    @field_validator("field")
    @classmethod
    def validate_field(cls, v): ...
    
    data = model.model_dump()

# WRONG — never do this  
@validator("field")
def validate_field(cls, v): ...
data = model.dict()
```
"""


def gen_anti_patterns_md(blueprint: dict[str, Any]) -> str:
    bp_anti_patterns = blueprint.get("anti_patterns", [])
    bp_lines: list[str] = []
    for ap in bp_anti_patterns:
        if isinstance(ap, str):
            bp_lines.append(f"- NEVER {ap}")
        elif isinstance(ap, dict):
            deprecated = ap.get("deprecated", "")
            use_instead = ap.get("use_instead", "")
            package = ap.get("package", "")
            if deprecated and use_instead:
                prefix = f"[{package}] " if package else ""
                bp_lines.append(f"- NEVER use `{deprecated}` → use `{use_instead}` {prefix}")

    bp_block = "\n".join(bp_lines) if bp_lines else "- (none specified beyond standard rules)"

    return f"""# ANTI_PATTERNS.md
# NEVER DO THESE. VIOLATIONS BREAK THE PRODUCT.

## Security
- NEVER store JWT in localStorage → httpOnly cookies only
- NEVER log or return decrypted API keys in any response
- NEVER trust user_id from request body → always from JWT token
- NEVER skip input validation on any endpoint
- NEVER use plain text API keys in memory longer than the API call
- NEVER commit .env or .env.local files

## FastAPI
- NEVER use sync def for DB or external API operations → async def only
- NEVER put business logic in routers → use services/
- NEVER return raw exceptions → always HTTPException with status code
- NEVER skip response_model on endpoint definitions
- NEVER use global state → use dependency injection

## SQLAlchemy 2.0
- NEVER use Query() API → use select() + await session.execute()
- NEVER use synchronous sessions in async context
- NEVER forget to await session operations
- NEVER use db.session Flask-style → use Depends(get_db)

## Pydantic v2
- NEVER use @validator → use @field_validator
- NEVER use .dict() → use .model_dump()
- NEVER use .json() → use .model_dump_json()
- NEVER mix Pydantic v1 and v2 patterns

## Next.js 14 App Router
- NEVER use pages/ directory → use app/ only
- NEVER use getServerSideProps → use Server Components + fetch()
- NEVER use _app.tsx → use app/layout.tsx
- NEVER import server-only code in client components

## Blueprint-specific Anti-patterns
{bp_block}

## File & State Management
- NEVER write generated files to disk before user approval
- NEVER advance project state without explicit user action
- NEVER expose raw error stack traces to end users
- NEVER hardcode API keys, secrets, or credentials
"""


def gen_dependencies_md(blueprint: dict[str, Any]) -> str:
    bp_deps = blueprint.get("dependencies", {})
    py_deps = bp_deps.get("python", [])
    npm_deps = bp_deps.get("npm", [])

    pip_lines: list[str] = []
    pip_install_parts: list[str] = []

    for dep in py_deps:
        if isinstance(dep, dict):
            name = dep.get("name", "")
            version = dep.get("version", "")
            purpose = dep.get("purpose", "")
            if name:
                spec = f"{name}=={version}" if version and version != "latest" else name
                pip_lines.append(f"{spec:<40} # {purpose}" if purpose else spec)
                pip_install_parts.append(spec)
        elif isinstance(dep, str):
            pip_lines.append(dep)
            pip_install_parts.append(dep)

    npm_lines: list[str] = []
    npm_install_parts: list[str] = []

    for dep in npm_deps:
        if isinstance(dep, dict):
            name = dep.get("name", "")
            version = dep.get("version", "")
            purpose = dep.get("purpose", "")
            if name:
                spec = f"{name}@{version}" if version and version != "latest" else name
                npm_lines.append(f"{spec:<50} # {purpose}" if purpose else spec)
                npm_install_parts.append(spec)
        elif isinstance(dep, str):
            npm_lines.append(dep)
            npm_install_parts.append(dep)

    pip_block = "\n".join(pip_lines) if pip_lines else "# (defined by blueprint tech_stack)"
    npm_block = "\n".join(npm_lines) if npm_lines else "# (defined by blueprint tech_stack)"
    pip_cmd = f"pip install {' '.join(pip_install_parts)}" if pip_install_parts else "pip install -r requirements.txt"
    npm_cmd = f"npm install {' '.join(npm_install_parts)}" if npm_install_parts else "npm install"

    return f"""# DEPENDENCIES.md
# EXACT VERSIONS. Install exactly as shown. Never substitute.

## Python Packages (backend/)
```bash
{pip_cmd}
```

{pip_block}

## npm Packages (frontend/)
```bash
{npm_cmd}
```

{npm_block}
"""


def generate_file_injection_guide(blueprint: dict[str, Any]) -> str:
    modules = blueprint.get("modules", [])
    sections: list[str] = [
        "# FILE_INJECTION_GUIDE.md",
        "## Module-to-File Injection Map\n",
    ]

    for m in modules:
        if not isinstance(m, dict):
            continue
        name = m.get("name", "Module")
        deps = m.get("depends_on", [])
        sections.append(f"### {name}")
        sections.append(f"Primary files to inject for building this module:")
        
        snake_name = name.lower().replace(" ", "_")
        sections.append(f"- backend/app/models/{snake_name}.py")
        sections.append(f"- backend/app/schemas/{snake_name}.py")
        sections.append(f"- backend/app/services/{snake_name}_service.py")
        sections.append(f"- backend/app/routers/{snake_name}.py")
        sections.append(f"- frontend/app/dashboard/{snake_name.replace('_', '-')}/page.tsx")
        
        if deps:
            sections.append(f"\nRequires context from modules: {', '.join(deps)}")
        sections.append("")

    return "\n".join(sections)


async def upload_to_storage(project_id: UUID, files: dict[str, str]) -> list[dict[str, Any]]:
    """Upload all files to Supabase Storage."""
    results = []
    
    supabase_url = settings.SUPABASE_URL
    service_key = settings.SUPABASE_SERVICE_KEY
    bucket = settings.SUPABASE_STORAGE_BUCKET

    async with httpx.AsyncClient(timeout=30.0) as client:
        for filename, content in files.items():
            path = f"{project_id}/{filename}"
            upload_url = f"{supabase_url}/storage/v1/object/{bucket}/{path}"
            
            try:
                resp = await client.post(
                    upload_url,
                    headers={
                        "Authorization": f"Bearer {service_key}",
                        "Content-Type": "text/plain; charset=utf-8",
                        "x-upsert": "true",
                    },
                    content=content.encode("utf-8")
                )
                
                if resp.status_code in (200, 201):
                    results.append({
                        "name": filename,
                        "url": f"{supabase_url}/storage/v1/object/public/{bucket}/{path}",
                        "size": len(content)
                    })
                else:
                    logger.error("Failed to upload %s: %s", filename, resp.text)
            except Exception as e:
                logger.error("Error uploading %s: %s", filename, e)

    return results
