from __future__ import annotations

import base64
import logging
import os
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

import httpx
from github import Github, GithubException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.core.encryption import encrypt, decrypt
from app.core.state_machine import advance_state
from app.models.execution_task import ExecutionTask
from app.models.github_push import GithubPush
from app.models.project import Project
from app.models.stage_output import StageOutput
from app.models.user import UserIntegration

logger = logging.getLogger(__name__)

# ── Constants ─────────────────────────────────────────────────────────────────

GITHUB_OAUTH_URL = "https://github.com/login/oauth/authorize"
GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token"
GITHUB_API_URL = "https://api.github.com"
COMMIT_MESSAGE = "Initial commit — generated by IdeaForge AI"
MIT_LICENSE = """\
MIT License

Copyright (c) {year} IdeaForge AI

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

# Files/patterns that must never be pushed (BUSINESS_LOGIC Stage 5)
EXCLUDED_PATTERNS: list[str] = [
    ".env",
    "__pycache__",
    "node_modules",
    ".next",
    ".pyc",
    "venv/",
    ".DS_Store",
]


# ── Exclusion filter ──────────────────────────────────────────────────────────

def _is_excluded(path: str) -> bool:
    """Return True if the file path matches any exclusion pattern."""
    for pattern in EXCLUDED_PATTERNS:
        if pattern.startswith(".") and not pattern.startswith(".env"):
            # Extension match (e.g. .pyc)
            if path.endswith(pattern):
                return True
        if pattern in path:
            return True
    # Never push bare .env (matches .env exactly or .env at path boundary)
    basename = os.path.basename(path)
    if basename == ".env":
        return True
    return False


# ── OAuth ─────────────────────────────────────────────────────────────────────

def get_oauth_url() -> str:
    """Build GitHub OAuth URL with repo scope."""
    params = (
        f"client_id={settings.GITHUB_CLIENT_ID}"
        f"&redirect_uri={settings.GITHUB_REDIRECT_URI}"
        f"&scope=repo"
    )
    return f"{GITHUB_OAUTH_URL}?{params}"


async def exchange_code_for_token(code: str) -> str:
    """POST to GitHub, return raw access_token string."""
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.post(
            GITHUB_TOKEN_URL,
            headers={"Accept": "application/json"},
            data={
                "client_id": settings.GITHUB_CLIENT_ID,
                "client_secret": settings.GITHUB_CLIENT_SECRET,
                "code": code,
            },
        )
    resp.raise_for_status()
    data = resp.json()
    token = data.get("access_token")
    if not token:
        error = data.get("error_description", data.get("error", "unknown"))
        raise ValueError(f"GitHub token exchange failed: {error}")
    return token


async def get_github_username(token: str) -> str:
    """GET /user, return login username."""
    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.get(
            f"{GITHUB_API_URL}/user",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
            },
        )
    resp.raise_for_status()
    return resp.json()["login"]


# ── Auto-generated file content ───────────────────────────────────────────────

def generate_readme(project: Project) -> str:
    """Generate README.md from project metadata."""
    name = getattr(project, "name", "IdeaForge Project")
    description = getattr(project, "description", "")
    idea = getattr(project, "structured_idea", None)

    idea_section = ""
    if idea and isinstance(idea, dict):
        core = idea.get("core_idea", description)
        target = idea.get("target_users", "")
        idea_section = f"\n## Overview\n{core}\n"
        if target:
            idea_section += f"\n**Target Users:** {target}\n"

    return f"""\
# {name}

> Generated by [IdeaForge AI](https://ideaforge.ai)
{idea_section}
## Setup

### Prerequisites
- Python 3.11+
- Node.js 18+
- PostgreSQL 15 (or Supabase account)

### Backend
```bash
cd backend
python -m venv venv
source venv/bin/activate  # Windows: venv\\Scripts\\activate
pip install -r requirements.txt
cp .env.example .env      # fill in your values
alembic upgrade head
uvicorn app.main:app --reload
```

### Frontend
```bash
cd frontend
npm install
cp .env.example .env.local  # fill in your values
npm run dev
```

## Environment Variables
Copy `.env.example` to `.env` and fill in the required values.

## License
MIT — see [LICENSE](LICENSE)
"""


def generate_gitignore() -> str:
    """Python + Node + env file exclusions."""
    return """\
# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd
.Python
venv/
.venv/
env/
*.egg-info/
dist/
build/
.mypy_cache/
.pytest_cache/
.ruff_cache/

# Environment
.env
.env.*
!.env.example

# Node
node_modules/
.next/
out/
.npm/
*.log

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
"""


def generate_env_example(project: Project) -> str:
    """Skeleton .env.example — no real values."""
    return """\
# Database
DATABASE_URL=postgresql+asyncpg://user:password@host:5432/dbname
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_SERVICE_KEY=your-service-role-key

# Auth
JWT_SECRET=change-me-to-a-long-random-string
JWT_ALGORITHM=HS256
JWT_EXPIRE_DAYS=7

# Encryption
FERNET_KEY=your-fernet-key

# GitHub OAuth
GITHUB_CLIENT_ID=your-github-client-id
GITHUB_CLIENT_SECRET=your-github-client-secret
GITHUB_REDIRECT_URI=http://localhost:3000/settings?tab=integrations

# AI Keys (BYOK)
ANTHROPIC_API_KEY=sk-ant-...
OPENAI_API_KEY=sk-...
GEMINI_API_KEY=...

# App
ENVIRONMENT=development
FRONTEND_URL=http://localhost:3000
"""


# ── File collection ───────────────────────────────────────────────────────────

async def _collect_approved_files(
    db: AsyncSession,
    project_id: UUID,
) -> list[dict[str, str]]:
    """Collect generated_files from all approved execution tasks."""
    result = await db.execute(
        select(ExecutionTask).where(
            ExecutionTask.project_id == project_id,
            ExecutionTask.status == "approved",
        )
    )
    tasks = list(result.scalars().all())
    files: list[dict[str, str]] = []
    for task in tasks:
        for f in task.generated_files or []:
            path = f.get("path", "")
            if path and not _is_excluded(path):
                files.append({"path": path, "content": f.get("content", "")})
    return files


def _build_file_tree(
    project: Project,
    approved_files: list[dict[str, str]],
) -> list[dict[str, str]]:
    """Merge approved files with auto-generated files; apply exclusion filter."""
    auto: list[dict[str, str]] = [
        {"path": "README.md",      "content": generate_readme(project)},
        {"path": ".gitignore",     "content": generate_gitignore()},
        {"path": ".env.example",   "content": generate_env_example(project)},
        {"path": "LICENSE",        "content": MIT_LICENSE.format(year=datetime.now().year)},
    ]
    # approved files may already contain README etc — auto-generated wins
    auto_paths = {f["path"] for f in auto}
    filtered_approved = [f for f in approved_files if f["path"] not in auto_paths]
    return auto + filtered_approved


# ── GitHub repo push ──────────────────────────────────────────────────────────

async def get_preview(
    db: AsyncSession,
    project_id: UUID,
    user_id: UUID,
) -> dict[str, Any]:
    """Return file list that would be pushed, without actually pushing."""
    project = await _get_project(db, project_id, user_id)
    approved = await _collect_approved_files(db, project_id)
    all_files = _build_file_tree(project, approved)
    auto_paths = ["README.md", ".gitignore", ".env.example", "LICENSE"]
    return {
        "files": [f["path"] for f in all_files],
        "auto_generated": auto_paths,
        "total": len(all_files),
    }


async def push_to_github(
    db: AsyncSession,
    project: Project,
    repo_name: str,
    is_private: bool,
    branch: str,
    github_token: str,
) -> dict[str, str]:
    """
    1. Collect approved files + auto-generated.
    2. Filter excluded.
    3. Create GitHub repo via PyGitHub.
    4. Single commit all files.
    5. Return { repo_url, commit_sha }.
    """
    import asyncio

    approved = await _collect_approved_files(db, project.id)
    all_files = _build_file_tree(project, approved)

    def _do_push() -> dict[str, str]:
        gh = Github(github_token)
        user = gh.get_user()

        # Create repo
        try:
            repo = user.create_repo(
                name=repo_name,
                private=is_private,
                auto_init=False,
                description=f"Generated by IdeaForge AI — {getattr(project, 'name', repo_name)}",
            )
        except GithubException as exc:
            raise ValueError(f"Repo creation failed: {exc.data.get('message', exc)}") from exc

        # Build git tree elements for a single commit
        blobs = []
        for f in all_files:
            content = f["content"]
            try:
                blob = repo.create_git_blob(content, "utf-8")
            except GithubException:
                # Binary fallback — encode as base64
                encoded = base64.b64encode(content.encode()).decode()
                blob = repo.create_git_blob(encoded, "base64")
            blobs.append(
                {
                    "path": f["path"],
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob.sha,
                }
            )

        # Create tree → commit → update ref
        tree = repo.create_git_tree(blobs)
        parent_commits: list[Any] = []  # empty = root commit

        commit = repo.create_git_commit(
            message=COMMIT_MESSAGE,
            tree=tree,
            parents=parent_commits,
        )

        # Create branch ref
        try:
            repo.create_git_ref(f"refs/heads/{branch}", commit.sha)
        except GithubException as exc:
            raise ValueError(f"Branch ref creation failed: {exc.data.get('message', exc)}") from exc

        return {"repo_url": repo.html_url, "commit_sha": commit.sha}

    # PyGitHub is sync → run in thread pool to avoid blocking event loop
    result = await asyncio.to_thread(_do_push)
    return result


# ── DB helpers ────────────────────────────────────────────────────────────────

async def _get_project(
    db: AsyncSession,
    project_id: UUID,
    user_id: UUID,
) -> Project:
    from fastapi import HTTPException

    result = await db.execute(
        select(Project).where(
            Project.id == project_id,
            Project.user_id == user_id,
        )
    )
    project = result.scalar_one_or_none()
    if not project:
        raise HTTPException(
            status_code=404,
            detail={"detail": "Project not found", "code": "PROJECT_NOT_FOUND"},
        )
    return project


async def _get_integration(
    db: AsyncSession,
    user_id: UUID,
    provider: str,
) -> UserIntegration | None:
    result = await db.execute(
        select(UserIntegration).where(
            UserIntegration.user_id == user_id,
            UserIntegration.provider == provider,
        )
    )
    return result.scalar_one_or_none()


async def save_push_result(
    db: AsyncSession,
    project_id: UUID,
    repo_name: str,
    branch: str,
    is_private: bool,
    result: dict[str, str],
) -> GithubPush:
    record = GithubPush(
        project_id=project_id,
        repo_url=result["repo_url"],
        repo_name=repo_name,
        branch=branch,
        is_private=is_private,
        commit_sha=result["commit_sha"],
        status="success",
        pushed_at=datetime.now(timezone.utc),
    )
    db.add(record)
    await db.commit()
    await db.refresh(record)
    return record


async def advance_state_to_pushed(
    db: AsyncSession,
    project_id: UUID,
    user_id: UUID,
) -> None:
    project = await _get_project(db, project_id, user_id)
    advance_state(project, "GITHUB_PUSHED")
    await db.commit()


# ── Integration store/retrieve helpers ───────────────────────────────────────

async def store_integration(
    db: AsyncSession,
    user_id: UUID,
    provider: str,
    access_token: str,
    username: str,
) -> UserIntegration:
    """Upsert encrypted integration token."""
    encrypted = encrypt(access_token)
    existing = await _get_integration(db, user_id, provider)
    if existing:
        existing.access_token = encrypted
        existing.username = username
        await db.commit()
        await db.refresh(existing)
        return existing
    record = UserIntegration(
        user_id=user_id,
        provider=provider,
        access_token=encrypted,
        username=username,
    )
    db.add(record)
    await db.commit()
    await db.refresh(record)
    return record


async def get_decrypted_token(
    db: AsyncSession,
    user_id: UUID,
    provider: str,
) -> str | None:
    """Return decrypted access token or None if not connected."""
    integration = await _get_integration(db, user_id, provider)
    if not integration:
        return None
    try:
        return decrypt(integration.access_token)
    except Exception:
        logger.warning("Fernet decryption failed for user=%s provider=%s", user_id, provider)
        return None


async def list_integrations(
    db: AsyncSession,
    user_id: UUID,
) -> list[dict[str, Any]]:
    """Return connection status for all known providers."""
    result = await db.execute(
        select(UserIntegration).where(UserIntegration.user_id == user_id)
    )
    rows = {r.provider: r for r in result.scalars().all()}
    providers = ["github", "vercel", "railway"]
    return [
        {
            "provider": p,
            "connected": p in rows,
            "username": rows[p].username if p in rows else None,
        }
        for p in providers
    ]


async def delete_integration(
    db: AsyncSession,
    user_id: UUID,
    provider: str,
) -> None:
    from fastapi import HTTPException

    integration = await _get_integration(db, user_id, provider)
    if not integration:
        raise HTTPException(
            status_code=404,
            detail={"detail": f"No {provider} integration found", "code": "INTEGRATION_NOT_FOUND"},
        )
    await db.delete(integration)
    await db.commit()