"""initial

Revision ID: 8940f4c4c752
Revises: 
Create Date: 2026-05-11 21:48:01.334030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8940f4c4c752'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployments', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_deployments_project', table_name='deployments')
    op.alter_column('execution_logs', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_execution_logs_project', table_name='execution_logs')
    op.drop_index('idx_execution_logs_task', table_name='execution_logs')
    op.alter_column('execution_tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_execution_tasks_project', table_name='execution_tasks')
    op.drop_index('idx_execution_tasks_status', table_name='execution_tasks')
    op.alter_column('github_pushes', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_projects_state', table_name='projects')
    op.drop_index('idx_projects_user_id', table_name='projects')
    op.alter_column('stage_outputs', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_stage_outputs_project', table_name='stage_outputs')
    op.drop_constraint('stage_outputs_project_id_stage_round_number_key', 'stage_outputs', type_='unique')
    op.create_unique_constraint('uq_stage_outputs_project_stage_round', 'stage_outputs', ['project_id', 'stage', 'round_number'])
    op.alter_column('user_api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('user_api_keys_user_id_provider_key', 'user_api_keys', type_='unique')
    op.create_unique_constraint('uq_user_api_keys_user_provider', 'user_api_keys', ['user_id', 'provider'])
    op.alter_column('user_integrations', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('user_integrations_user_id_provider_key', 'user_integrations', type_='unique')
    op.create_unique_constraint('uq_user_integrations_user_provider', 'user_integrations', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_integrations_user_provider', 'user_integrations', type_='unique')
    op.create_unique_constraint('user_integrations_user_id_provider_key', 'user_integrations', ['user_id', 'provider'])
    op.alter_column('user_integrations', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_user_api_keys_user_provider', 'user_api_keys', type_='unique')
    op.create_unique_constraint('user_api_keys_user_id_provider_key', 'user_api_keys', ['user_id', 'provider'])
    op.alter_column('user_api_keys', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_stage_outputs_project_stage_round', 'stage_outputs', type_='unique')
    op.create_unique_constraint('stage_outputs_project_id_stage_round_number_key', 'stage_outputs', ['project_id', 'stage', 'round_number'])
    op.create_index('idx_stage_outputs_project', 'stage_outputs', ['project_id'], unique=False)
    op.alter_column('stage_outputs', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_index('idx_projects_state', 'projects', ['current_state'], unique=False)
    op.alter_column('projects', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('github_pushes', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_execution_tasks_status', 'execution_tasks', ['status'], unique=False)
    op.create_index('idx_execution_tasks_project', 'execution_tasks', ['project_id'], unique=False)
    op.alter_column('execution_tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_execution_logs_task', 'execution_logs', ['task_id'], unique=False)
    op.create_index('idx_execution_logs_project', 'execution_logs', ['project_id'], unique=False)
    op.alter_column('execution_logs', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_deployments_project', 'deployments', ['project_id'], unique=False)
    op.alter_column('deployments', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
